services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      FRONTEND_DIR: /frontend
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
      - sqlite_data:/app/data

volumes:
  sqlite_data:
